import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testgit',
  templateUrl: './testgit.page.html',
  styleUrls: ['./testgit.page.scss'],
})

export class TestgitPage implements OnInit {

  sart:number;
  sayac1:number;
  yanit1:boolean;
  yanit2:boolean;
  yanit3:boolean;
  yanit4:boolean;
  yanit5:boolean;
  yanit6:boolean;
  yanit7:boolean;
  yanit8:boolean;
  yanit9:boolean;
  yanit10:boolean;
  yanit11:boolean;
  yanit12:boolean;
  yanit13:boolean;
  yanit14:boolean;
  yanit15:boolean;
  yanit16:boolean;
  yanit17:boolean;
  yanit18:boolean;
  yanit19:boolean;
  yanit20:boolean;
  yanit21:boolean;
  yanit22:boolean;
  yanit23:boolean;
  yanit24:boolean;
  yanit25:boolean;
  yanit26:boolean;
  yanit27:boolean;
  yanit28:boolean;
  yanit29:boolean;
  yanit30:boolean;
  yanit31:boolean;
  yanit32:boolean;
  yanit33:boolean;
  yanit34:boolean;
  yanit35:boolean;
  yanit36:boolean;
  yanit37:boolean;
  yanit38:boolean;
  yanit39:boolean;
  yanit40:boolean;
  yanit41:boolean;
  yanit42:boolean;
  yanit43:boolean;
  yanit44:boolean;
  yanit45:boolean;


  constructor() { }
  ngOnInit() {}

  hesapla()
  {
    this.sayac1=0;
    if(this.yanit1==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit2==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit3==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit4==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit5==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit6==true)
    {
      this.sayac1=this.sayac1+7;
    }
     if(this.yanit7==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit8==true)
    {
      this.sayac1=this.sayac1+1;
    }
     if(this.yanit9==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit10==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit11==true)
    {
      this.sayac1=this.sayac1+5;
    }
     if(this.yanit12==true)
    {
      this.sayac1=this.sayac1+7;
    }
     if(this.yanit13==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit14==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit15==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit16==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit17==true)
    {
      this.sayac1=this.sayac1+1;
    }
     if(this.yanit18==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit19==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit20==true)
    {
      this.sayac1=this.sayac1+3;
    }
     if(this.yanit21==true)
    {
      this.sayac1=this.sayac1+5;
    }
     if(this.yanit22==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit23==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit24==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit25==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit26==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit27==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit28==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit29==true)
    {
      this.sayac1=this.sayac1+7;
    }
     if(this.yanit30==true)
    {
      this.sayac1=this.sayac1+5;
    }
     if(this.yanit31==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit32==true)
    {
      this.sayac1=this.sayac1+3;
    }
     if(this.yanit33==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit34==true)
    {
      this.sayac1=this.sayac1+1;
    }
     if(this.yanit35==true)
    {
      this.sayac1=this.sayac1+7;
    }
     if(this.yanit36==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit37==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit38==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit39==true)
    {
      this.sayac1=this.sayac1+1;
    }
     if(this.yanit40==true)
    {
      this.sayac1=this.sayac1+4;
    }
     if(this.yanit41==true)
    {
      this.sayac1=this.sayac1+2;
    }
     if(this.yanit42==true)
    {
      this.sayac1=this.sayac1+3;
    }
     if(this.yanit43==true)
    {
      this.sayac1=this.sayac1+5;
    }
     if(this.yanit44==true)
    {
      this.sayac1=this.sayac1+6;
    }
     if(this.yanit45==true)
    {
      this.sayac1=this.sayac1+1;
    }
    
    
  }

  yazdir()
  {
    if(this.sayac1>=31 && this.sayac1<=40)
    {
        this.sart=1;
    }
     if(this.sayac1>=41 && this.sayac1<=50)
    {
      this.sart=2;
    }
     if(this.sayac1>=51 && this.sayac1<=60)
    {
      this.sart=3;
    }
    if(this.sayac1>=61){
      this.sart=4;
    }
  }
 

}
